version: '2'
services:
  seed-app:
    image: seed
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://seed-postgresql:5432/seed
      - JHIPSTER_CACHE_MEMCACHED_SERVERS=seed-memcached:11211
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://seed-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://seed-elasticsearch:9200
    ports:
      - 8080:8080
  seed-postgresql:
    extends:
      file: postgresql.yml
      service: seed-postgresql
  seed-memcached:
    extends:
      file: memcached.yml
      service: seed-memcached
  seed-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: seed-elasticsearch
